from dotenv import load_dotenv
load_dotenv()
import os

OPENROUTER_API_KEY=os.getenv("OPENROUTER_API_KEY")
GROQ_API_KEY=os.getenv("GROQ_API_KEY")
SLACK_BOT_TOKEN=os.getenv("SLACK_BOT_TOKEN")
GITHUB_OAUTH_CLIENT_ID = os.getenv("GITHUB_OAUTH_CLIENT_ID")
GITHUB_OAUTH_CLIENT_SECRET = os.getenv("GITHUB_OAUTH_CLIENT_SECRET")